name: Build and Deploy MindTracking API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t mindtrack/mindtracking-api:latest .

      - name: Push Docker image
        run: docker push mindtrack/mindtracking-api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub (deploy host)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Create Docker network (if not exists)
        run: |
          if ! docker network inspect mindtrack-net &> /dev/null; then
            docker network create mindtrack-net;
          fi

      - name: Stop and remove old container (if running)
        run: |
          docker stop mindtracking-api || true
          docker rm mindtracking-api || true

      - name: Pull latest API image
        run: docker pull mindtrack/mindtracking-api:latest

      - name: Run API container with secrets
        shell: bash
        run: |
          set -euxo pipefail
          IMAGE="mindtrack/mindtracking-api:latest"
          echo "Running image: ${IMAGE}"
          docker run -d --restart always --name mindtracking-api --network mindtrack-net -p 80:3000 \
            -e API_KEY='${{ secrets.API_KEY }}' \
            -e DB_HOST='${{ secrets.DB_HOST }}' \
            -e DB_NAME='${{ secrets.DB_NAME }}' \
            -e DB_USER='${{ secrets.DB_USER }}' \
            -e DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
            -e DB_PORT='${{ secrets.DB_PORT }}' \
            -e EMAIL_USER='${{ secrets.EMAIL_USER }}' \
            -e EMAIL_PASS='${{ secrets.EMAIL_PASS }}' \
            -e JWT_KEY='${{ secrets.JWT_KEY }}' \
            "${IMAGE}"
